title: Siddhartha Khatri
logo: /assets/img/siddhartha.jpg
description: Full stack developer having more than 10 year of experience in application development.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
